MAKSIMALNA_BRZINA_ZAPADNI_SEKTOR=60
BROJ_VOZILA_ZAPADNI_SEKTOR=42
MAKSIMALNA_BRZINA_CENTRALNI_SEKTOR=220
BROJ_VOZILA_CENTRALNI_SEKTOR=45
MAKSIMALNA_BRZINA_ISTOCNI_SEKTOR=380
BROJ_VOZILA_ISTOCNI_SEKTOR=38
PUTANJA_DO_DIREKTORIJUMA_ZA_LINIJE=trains
PUTANJA_DO_DIREKTORIJUMA_ZA_SERIJALIZACJU=movement
PUTANJA_DO_DIREKTORIJUMA_ZA_RESURSE=resources
POCETAK_KREIRANJA_VOZILA=5000
INTERVAL_KREIRANJA_VOZILA=2000